services:
  yolo:
    build:
      context: .
    volumes:
      - ${YOLO_STORAGE_PATH:-./storage}:/data:ro
      - ${YOLO_MODELS_PATH:-./models}:/models
    ports:
      - "8001:8001"
    restart: unless-stopped
    shm_size: 4gb
